
import SidebarComp from "@/components/common/sidebar";

export const metadata = {
  title: "Tinder Lite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SidebarComp>
      {children}
    </SidebarComp>
  );
}

